// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ9B_miE3aHaI-Xp4ecqqzyy2G3ZAhCXs',
    appId: '1:522075253062:web:4a52f071eb310e72b05d47',
    messagingSenderId: '522075253062',
    projectId: 'hkexpo-5ed70',
    authDomain: 'hkexpo-5ed70.firebaseapp.com',
    storageBucket: 'hkexpo-5ed70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAiQqTqpPqTba2zI9SzeO3i1E2ClGCmbY',
    appId: '1:522075253062:android:6c2ef5182b953e0fb05d47',
    messagingSenderId: '522075253062',
    projectId: 'hkexpo-5ed70',
    storageBucket: 'hkexpo-5ed70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbSgPfwAZNBjtQOtUW8iI1R91e6E4Xr_c',
    appId: '1:522075253062:ios:d8445501bba4592fb05d47',
    messagingSenderId: '522075253062',
    projectId: 'hkexpo-5ed70',
    storageBucket: 'hkexpo-5ed70.firebasestorage.app',
    iosBundleId: 'com.example.lib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbSgPfwAZNBjtQOtUW8iI1R91e6E4Xr_c',
    appId: '1:522075253062:ios:d8445501bba4592fb05d47',
    messagingSenderId: '522075253062',
    projectId: 'hkexpo-5ed70',
    storageBucket: 'hkexpo-5ed70.firebasestorage.app',
    iosBundleId: 'com.example.lib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ9B_miE3aHaI-Xp4ecqqzyy2G3ZAhCXs',
    appId: '1:522075253062:web:4ae4234226388294b05d47',
    messagingSenderId: '522075253062',
    projectId: 'hkexpo-5ed70',
    authDomain: 'hkexpo-5ed70.firebaseapp.com',
    storageBucket: 'hkexpo-5ed70.firebasestorage.app',
  );
}
