default_agent: travelAgent_Agent
agents:
  travelAgent_Agent:
    name: travelAgent_Agent
    language: python
    node_version: null
    entrypoint: /Users/asyaunal/sightseeker_app/backend/bedrock-agent/travelAgent/src/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_10
    platform: linux/amd64
    container_runtime: null
    source_path: /Users/asyaunal/sightseeker_app/backend/bedrock-agent/travelAgent/src
    aws:
      execution_role: arn:aws:iam::975263988636:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-471a106b79
      execution_role_auto_create: false
      account: '975263988636'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-975263988636-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: travelAgent_Agent-HET7Du6ZKx
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:975263988636:runtime/travelAgent_Agent-HET7Du6ZKx
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: travelAgent_Agent_mem-rB6Axs8YmL
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:975263988636:memory/travelAgent_Agent_mem-rB6Axs8YmL
      memory_name: travelAgent_Agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: OPENAI_API_KEY
    api_key_credential_provider_name: travelagent_agent_openai_api_key
    is_generated_by_agentcore_create: true
